[package]
name = "midpad"
description = "Command line utility to pad texts."
license = "MIT"
authors = ["Rhelv"]
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"]}
anyhow = "1"
